---
- name: Automate Oremax Web Infrastructure Core
  hosts: local
  become: true

  vars:
    deployment_title: "Oremax Innovations Lifecycle"
    environment_profile: "Staging-Labs"

  tasks:
    - name: Ensure Nginx is installed on the system
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx service is started and enabled on boot
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy dynamic infrastructure health page via Jinja2 Template
      ansible.builtin.template:
        src: templates/health_page.html.j2
        dest: /var/www/html/index.nginx-debian.html
        mode: '0644'
